services:
  grpc-server:
    image: ghcr.io/apoorva64/eternity2/api:latest
    ports:
      - "50051:50051"
    build:
      context: .
      dockerfile: api/Dockerfile

  envoy:
    image: ghcr.io/apoorva64/eternity2/envoy:latest
    environment:
      - SOLVER_API=grpc-server
    build:
      context: envoy
    ports:
      - "50052:50052"
