services:
  grpc-server:
    container_name: grpc-server
    image: ghcr.io/startupnationlabs/eternity2/grpc-server:latest
    networks:
      - eternity2

  envoy:
    image: ghcr.io/startupnationlabs/eternity2/envoy:latest
    environment:
      - SOLVER_API=grpc-server
    ports:
      - "50052:50052"
    networks:
      - eternity2

  frontend:
    container_name: frontend
    image: ghcr.io/startupnationlabs/eternity2/frontend:latest
    ports:
      - "80:80"

networks:
  eternity2:
