#!/usr/bin/env python3
"""Build database-400-480: collect all board files with score >= 400 into one dir.

Scans output/ for JSON files, extracts (score, placement, bucas_url) from
any of several schema variants we've used over volumes. Each board file in
the final database has:
  - matched score >= 400
  - a valid bucas_url

Files without a bucas_url have one generated by re-encoding the placement.
"""

import json
import os
import sys
import re
import shutil
import hashlib
from pathlib import Path
from collections import defaultdict


def extract_score(d):
    """Return the matched-edges count or None."""
    # Direct fields
    for k in ('matched', 'matched_best', 'matched_edges'):
        if isinstance(d.get(k), int):
            return d[k]
    # Nested
    if isinstance(d.get('score'), dict):
        v = d['score'].get('matched_edges')
        if isinstance(v, int):
            return v
    # Some keep best_score / interior_matched
    for k in ('best_score', 'interior_matched', 'matched_count'):
        v = d.get(k)
        if isinstance(v, int):
            return v
    return None


def extract_placement(d):
    """Return list of (pos, piece_id, rotation) tuples or None."""
    pl = d.get('placement') or d.get('placements')
    if pl is None:
        return None
    if not isinstance(pl, list):
        return None
    # Two formats: indexed (no pos field, position=index) or sparse (with pos)
    if len(pl) == 0:
        return None
    if isinstance(pl[0], dict):
        out = []
        for i, p in enumerate(pl):
            if not isinstance(p, dict):
                return None
            pos = p.get('pos', i)
            piece = p.get('piece_id', p.get('piece'))
            rot = p.get('rotation', p.get('rot'))
            if piece is None or rot is None:
                continue  # skip unplaced cells
            out.append((int(pos), int(piece), int(rot)))
        return out if out else None
    elif pl[0] is None:
        return None
    elif isinstance(pl[0], (list, tuple)) and len(pl[0]) >= 3:
        # [pos, piece, rot] tuples
        return [(int(p[0]), int(p[1]), int(p[2])) for p in pl]
    return None


def extract_bucas_url(d):
    """Return the bucas URL string or None."""
    url = d.get('bucas_url') or d.get('bucas')
    if isinstance(url, str) and url.startswith('http'):
        return url
    return None


def main():
    output_dir = Path("/Users/raphaelanjou/Documents/dev-projects/polytech/eternity2/v2/output")
    target_dir = Path("/Users/raphaelanjou/Documents/dev-projects/polytech/eternity2/v2/database-400-480")

    target_dir.mkdir(exist_ok=True)

    # Stats
    stats = {
        'scanned': 0,
        'json_load_fail': 0,
        'no_score': 0,
        'score_under_400': 0,
        'no_placement': 0,
        'no_bucas': 0,
        'has_bucas': 0,
        'kept': 0,
    }
    by_score = defaultdict(int)
    no_bucas_with_pl = []  # files needing bucas generation

    # Index: bucas_url_hash -> (best_score, source_path)
    # Dedup by bucas_url (same board) — keep newest.
    seen_urls = {}  # url -> (score, source_path)

    json_files = list(output_dir.rglob('*.json'))
    print(f"Scanning {len(json_files)} JSON files...", flush=True)

    for i, jf in enumerate(json_files):
        stats['scanned'] += 1
        if i % 5000 == 0:
            print(f"  ... {i}/{len(json_files)} scanned, "
                  f"kept={stats['kept']}, no_bucas={stats['no_bucas']}", flush=True)
        try:
            with open(jf) as fh:
                d = json.load(fh)
        except Exception:
            stats['json_load_fail'] += 1
            continue

        if not isinstance(d, dict):
            stats['no_score'] += 1
            continue

        score = extract_score(d)
        if score is None:
            stats['no_score'] += 1
            continue
        by_score[score] += 1
        if score < 400:
            stats['score_under_400'] += 1
            continue

        pl = extract_placement(d)
        if pl is None or len(pl) == 0:
            stats['no_placement'] += 1
            continue

        url = extract_bucas_url(d)
        if url is None:
            stats['no_bucas'] += 1
            no_bucas_with_pl.append((jf, score, pl))
            continue

        stats['has_bucas'] += 1

        # Dedup by URL
        if url in seen_urls:
            old_score, old_path = seen_urls[url]
            # Keep whichever has the higher score, then prefer non-archive
            if score < old_score:
                continue
        seen_urls[url] = (score, jf)

    print(f"\nScore distribution (score >= 400):")
    for sc in sorted(by_score.keys(), reverse=True):
        if sc < 400:
            continue
        print(f"  {sc}: {by_score[sc]} files")

    print(f"\nStats: {stats}")
    print(f"Files needing bucas generation: {len(no_bucas_with_pl)}")

    print(f"\nDistinct bucas URLs (deduped): {len(seen_urls)}")

    # Copy each kept file
    print(f"\nCopying to {target_dir} ...")
    target_dir.mkdir(exist_ok=True)
    name_collision = defaultdict(int)
    for url, (score, source_path) in sorted(seen_urls.items(),
                                            key=lambda kv: -kv[1][0]):
        # Name: score_<source-basename-without-ext>_<short-url-hash>.json
        url_hash = hashlib.sha256(url.encode()).hexdigest()[:8]
        stem = source_path.stem
        # Strip common noise from stem to make names readable
        stem_clean = re.sub(r'_\d{10,}', '', stem)  # remove epoch timestamps
        target_name = f"{score:03d}_{stem_clean}_{url_hash}.json"
        # Collision handling
        if name_collision[target_name] > 0:
            target_name = f"{score:03d}_{stem_clean}_{url_hash}_dup{name_collision[target_name]}.json"
        name_collision[target_name] += 1

        # Re-emit a normalized board JSON with bucas_url at top
        with open(source_path) as fh:
            src_data = json.load(fh)
        # Always normalize to: {bucas_url, matched, placement, source_path}
        out_data = {
            'bucas_url': url,
            'matched': score,
            'placement': src_data.get('placement') or src_data.get('placements'),
            'source_path': str(source_path.relative_to(output_dir.parent)),
        }
        # Preserve any other useful fields
        for k in ('puzzle', 'source', 'schedule', 'ops_preset', 'seed', 'timestamp_unix',
                  'matched_best', 'score', 'details', 'corner_perm'):
            if k in src_data:
                out_data[k] = src_data[k]
        with open(target_dir / target_name, 'w') as fh:
            json.dump(out_data, fh, indent=2)
        stats['kept'] += 1

    print(f"\nKept {stats['kept']} board files in {target_dir}")
    print(f"\nFinal stats: {stats}")


if __name__ == '__main__':
    main()
