#!/usr/bin/env python3
"""Selby-Riordan generator-bias statistical diagnostic.

Tests M1 agent's H1: the Eternity II piece set was generated by
Selby & Riordan with adversarial bias to defeat their own E1 solver.
If true, the color statistics should differ from a uniform-random
piece set of the same size.

We compute, on the official piece-set:
 - per-color edge count (should be roughly equal in random; bias may
   over-equalise to maximise minimum entropy)
 - per-color N/S vs E/W imbalance
 - color-pair co-occurrence (which colors appear adjacent within a piece)
 - parity of color counts

Then compare against:
 - the theoretical "ideal uniform" expectation
 - a Monte-Carlo sample of random piece sets with the same color counts

Output: a structural fingerprint of the piece set, and a chi-square
distance from uniform.
"""

import csv
import math
import random
import statistics
from collections import Counter, defaultdict
from pathlib import Path

PUZZLE = Path(__file__).parent.parent.parent / "data" / "puzzles" / "size_16_official_eternity.csv"
BORDER = 65535
N_SAMPLES = 1000  # Monte Carlo samples for random piece sets


def parse_color(s):
    v = int(s.strip(), 2)
    return -1 if v == BORDER else v


def load_pieces():
    """Return list of (top, right, bottom, left) for each piece."""
    pieces = []
    with PUZZLE.open() as f:
        lines = [ln.strip() for ln in f if ln.strip()]
    size = int(lines[0])
    for ln in lines[1:]:
        cols = ln.split(",")
        top, right, bottom, left = (parse_color(c) for c in cols[:4])
        pieces.append((top, right, bottom, left))
    return size, pieces


def edge_classify(piece):
    """Return ('corner', 'edge', 'interior')."""
    borders = sum(1 for c in piece if c == -1)
    if borders == 2:
        return "corner"
    if borders == 1:
        return "edge"
    if borders == 0:
        return "interior"
    return "??"


def color_stats(pieces):
    """Return per-color totals and N/S vs E/W counts on interior edges."""
    total = Counter()        # color -> total occurrences (all 4 edges)
    ns_count = Counter()     # color -> count on N or S edges
    ew_count = Counter()     # color -> count on E or W edges
    for top, right, bottom, left in pieces:
        for c in (top, bottom):
            if c >= 0:
                total[c] += 1
                ns_count[c] += 1
        for c in (right, left):
            if c >= 0:
                total[c] += 1
                ew_count[c] += 1
    return total, ns_count, ew_count


def color_pair_within_piece(pieces):
    """Return Counter of unordered color pairs co-occurring on the same piece."""
    co = Counter()
    for piece in pieces:
        inside = [c for c in piece if c >= 0]
        for i, ci in enumerate(inside):
            for cj in inside[i + 1 :]:
                if ci == cj:
                    continue
                key = (min(ci, cj), max(ci, cj))
                co[key] += 1
    return co


def chi_square_uniform(counts, n_categories):
    """Chi-square test of given counts vs uniform on n_categories.
    Returns chi2 stat. Larger = more deviation from uniform.
    """
    total = sum(counts.values())
    expected = total / n_categories
    chi2 = sum((c - expected) ** 2 / expected for c in counts.values())
    # Categories that didn't appear:
    chi2 += (n_categories - len(counts)) * expected
    return chi2


def mc_chi2(pieces, n_samples=N_SAMPLES, seed=0xCAFE):
    """Monte-Carlo: shuffle the multiset of edge colors across pieces,
    keeping per-piece edge count constant. Report distribution of chi2
    of resulting color totals."""
    rng = random.Random(seed)
    # Edges (color values, including -1 borders) flattened.
    all_edges = [c for piece in pieces for c in piece]
    n_interior_colors = max(c for c in all_edges if c >= 0) + 1
    chi2s = []
    for _ in range(n_samples):
        shuffled = all_edges[:]
        rng.shuffle(shuffled)
        total = Counter(c for c in shuffled if c >= 0)
        chi2s.append(chi_square_uniform(total, n_interior_colors))
    return chi2s


def parity_signature(counts):
    """Return tuple (even_colors, odd_colors)."""
    even = [c for c, k in counts.items() if k % 2 == 0]
    odd = [c for c, k in counts.items() if k % 2 == 1]
    return len(even), len(odd)


def co_occurrence_stats(co):
    """Color-pair co-occurrence statistics."""
    vals = list(co.values())
    return {
        "n_pairs_seen": len(co),
        "median": statistics.median(vals),
        "mean": statistics.mean(vals),
        "min": min(vals),
        "max": max(vals),
        "stdev": statistics.pstdev(vals),
    }


def main():
    size, pieces = load_pieces()
    print(f"loaded {len(pieces)} pieces from {size}x{size} puzzle\n")

    classes = Counter(edge_classify(p) for p in pieces)
    print(f"piece classes: {dict(classes)}")

    total, ns, ew = color_stats(pieces)
    interior_colors = sorted(total.keys())
    n_int = max(interior_colors) + 1 if interior_colors else 0
    print(f"\n22 interior colors? n_int={n_int}; colors found: {len(interior_colors)}")

    # Per-color totals
    print(f"\nper-color edge totals (interior only; rare 1-5 expected at 24 each):")
    by_count = sorted(total.items(), key=lambda x: x[1])
    for c, k in by_count:
        bar = "#" * (k // 2)
        marker = " *RARE*" if k <= 26 else " *abundant*" if k >= 48 else ""
        print(f"  color {c:2d}: {k:4d}  {bar}{marker}")

    # N/S vs E/W imbalance per color
    print(f"\nN/S vs E/W imbalance (positive ⇒ more N/S, negative ⇒ more E/W):")
    imbal = []
    for c in interior_colors:
        delta = ns.get(c, 0) - ew.get(c, 0)
        imbal.append((c, delta, ns.get(c, 0), ew.get(c, 0)))
    imbal.sort(key=lambda x: abs(x[1]), reverse=True)
    for c, delta, n, e in imbal:
        print(f"  color {c:2d}: NS={n:3d} EW={e:3d} delta={delta:+4d}")

    # Chi-square: observed totals vs uniform
    obs_chi2 = chi_square_uniform(total, n_int)
    print(f"\nchi-square (observed totals vs uniform across {n_int} colors): {obs_chi2:.2f}")

    # Monte-Carlo chi2 distribution
    print(f"\nrunning Monte-Carlo ({N_SAMPLES} samples) of random color shufflings...")
    mc = mc_chi2(pieces, N_SAMPLES)
    mc_mean = statistics.mean(mc)
    mc_stdev = statistics.pstdev(mc)
    mc_p_lower = sum(1 for v in mc if v <= obs_chi2) / len(mc)
    print(f"  MC chi2:  mean={mc_mean:.2f}  stdev={mc_stdev:.2f}  min={min(mc):.2f}  max={max(mc):.2f}")
    print(f"  P(MC chi2 ≤ observed) = {mc_p_lower:.4f}  (low value ⇒ observed is UNUSUALLY UNIFORM)")
    print(f"  if P(MC chi2 ≤ obs) < 0.05, the official piece set is statistically *flatter* than random")

    # Parity
    even, odd = parity_signature(total)
    print(f"\ncolor parity: {even} even-count colors, {odd} odd-count")
    print("  (even count ⇒ all edges can match internally; odd ⇒ some unavoidable mismatch)")

    # Color-pair co-occurrence
    print("\ncolor-pair co-occurrence WITHIN a piece (4-edge pieces have C(4,2)=6 pairs each):")
    co = color_pair_within_piece(pieces)
    cs = co_occurrence_stats(co)
    for k, v in cs.items():
        print(f"  {k}: {v:.3f}" if isinstance(v, float) else f"  {k}: {v}")

    print("\nrarest color-pair (in-piece adjacency):")
    sorted_co = sorted(co.items(), key=lambda x: x[1])
    for (a, b), k in sorted_co[:10]:
        print(f"  ({a:2d},{b:2d}): {k} pieces")
    print("\nmost-common color-pair (in-piece adjacency):")
    for (a, b), k in sorted_co[-10:]:
        print(f"  ({a:2d},{b:2d}): {k} pieces")

    # Are there color pairs that DON'T co-occur in any piece?
    interior_set = set(interior_colors)
    missing = []
    for a in interior_colors:
        for b in interior_colors:
            if a >= b:
                continue
            if (a, b) not in co:
                missing.append((a, b))
    print(f"\ncolor pairs that NEVER co-occur within a piece: {len(missing)}")
    if missing and len(missing) <= 20:
        for a, b in missing:
            print(f"  ({a:2d},{b:2d})")
    elif len(missing) > 20:
        print(f"  (showing first 20 of {len(missing)})")
        for a, b in missing[:20]:
            print(f"  ({a:2d},{b:2d})")


if __name__ == "__main__":
    main()
