#!/usr/bin/env python3
"""Vol-106 — Relax-and-Cross / Constraint-Vote Crossover (CVC) v1.

Algorithm class invented by Raphael Anjou (2026-05-16). See
`vault/concepts/relax-and-cross-cvc.md` for authorship reservation.

This v1 prototype:
1. Reads a small puzzle (e.g. 8×8 / 7-color generated by
   eternity2-generator + dump_puzzle_csv).
2. Solves the puzzle EXACTLY (DFS backtracker — tractable at 8×8).
3. For each color k ∈ {1..C}, solves a RELAXED puzzle where edges
   originally of color k are WILDCARDS that match any color.
4. Cross-votes per cell: builds a consensus board by majority over
   (piece, rotation) at each position. Repairs piece-uniqueness via
   greedy (vote-weighted) Hungarian-like assignment.
5. Scores the consensus board against the ORIGINAL (no relaxation)
   puzzle.

Outputs:
- score of original optimum (the goal).
- score of each relaxed-puzzle optimum.
- score of the cross-voted consensus board.
- comparison: does consensus > max single relaxed?

Usage:
    vol106_cvc_v1.py <puzzle.csv> [--max-seconds-per-relax 60]
"""

import argparse
import json
import sys
import time
from pathlib import Path

# ----- puzzle parsing -----

def bitmask_to_color(bs):
    """16-bit binary string. All-1s = BORDER (color 0). One-hot = color
    1..16 (position of the '1' bit from LSB, 1-indexed)."""
    bs = bs.strip()
    if all(c == '1' for c in bs):
        return 0  # BORDER
    # Find position of '1' from the right (LSB)
    for i, c in enumerate(reversed(bs)):
        if c == '1':
            return i + 1
    raise ValueError(f"empty bitmask {bs!r}")


def parse_puzzle(path):
    """Returns (size, pieces) where pieces is a list of (n, e, s, w)
    color tuples, 0-indexed (piece_id = list index)."""
    with open(path) as f:
        lines = f.read().splitlines()
    size = int(lines[0])
    pieces = []
    for line in lines[1:]:
        if not line.strip():
            continue
        parts = line.split(',')
        n = bitmask_to_color(parts[0])
        e = bitmask_to_color(parts[1])
        s = bitmask_to_color(parts[2])
        w = bitmask_to_color(parts[3])
        pieces.append((n, e, s, w))
    return size, pieces


def rotate_edges(e, r):
    n, ee, s, w = e
    if r == 0:
        return (n, ee, s, w)
    elif r == 1:
        return (w, n, ee, s)
    elif r == 2:
        return (s, w, n, ee)
    elif r == 3:
        return (ee, s, w, n)


# ----- exact backtracker for small puzzles -----

def solve_optimum(size, pieces, wildcard_color=None, max_seconds=60):
    """DFS backtracker for ALL-MATCHING solution (or best partial). For
    small puzzles + low-color, returns a complete board with all
    interior edges matching ORIGINAL puzzle, except edges of color
    `wildcard_color` which match anything.

    Strategy: row-major DFS, place piece at each cell, pick from
    remaining pieces compatible with already-placed neighbors.

    Returns (placement_dict, score, time_seconds, exhaustive_done) where
    placement_dict maps pos → (piece_id, rotation).

    For 8×8 / 7c the solution should exist and be findable in seconds.
    """
    n_cells = size * size
    n_pieces = len(pieces)
    assert n_pieces == n_cells

    # Precompute: for each piece, all 4 rotations.
    pieces_rot = [[rotate_edges(p, r) for r in range(4)] for p in pieces]

    # Wildcard matching: returns True if edge colors a, b match.
    # If wildcard_color is None: standard match (a == b, both nonzero or both border).
    # If wildcard_color set: also matches if a == wildcard_color or b == wildcard_color.
    if wildcard_color is None:
        def edge_match(a, b):
            return a == b
    else:
        wc = wildcard_color
        def edge_match(a, b):
            return a == b or a == wc or b == wc

    # Border-compatibility: cell at (x, y) requires:
    # - top edge = BORDER (0) if y == 0
    # - left edge = BORDER (0) if x == 0
    # - bottom edge = BORDER (0) if y == size-1
    # - right edge = BORDER (0) if x == size-1
    # else: must match neighbor's adjacent edge.

    placement = {}
    used = [False] * n_pieces
    best = {'score': -1, 'placement': None}

    t_start = time.time()
    nodes_explored = [0]
    timeout = [False]

    def cell_constraints(pos):
        """Return tuple (need_top, need_right, need_bottom, need_left)
        where each is a color (0..max) the cell's edge must equal, or
        None if it's free (no neighbor placed in that direction)."""
        x, y = pos % size, pos // size
        # Top
        if y == 0:
            need_top = 0
        else:
            neighbor_pos = pos - size
            if neighbor_pos in placement:
                pid, rot = placement[neighbor_pos]
                n, e, s, w = pieces_rot[pid][rot]
                need_top = s
            else:
                need_top = None
        # Right
        if x == size - 1:
            need_right = 0
        else:
            neighbor_pos = pos + 1
            if neighbor_pos in placement:
                pid, rot = placement[neighbor_pos]
                n, e, s, w = pieces_rot[pid][rot]
                need_right = w
            else:
                need_right = None
        # Bottom
        if y == size - 1:
            need_bottom = 0
        else:
            neighbor_pos = pos + size
            if neighbor_pos in placement:
                pid, rot = placement[neighbor_pos]
                n, e, s, w = pieces_rot[pid][rot]
                need_bottom = n
            else:
                need_bottom = None
        # Left
        if x == 0:
            need_left = 0
        else:
            neighbor_pos = pos - 1
            if neighbor_pos in placement:
                pid, rot = placement[neighbor_pos]
                n, e, s, w = pieces_rot[pid][rot]
                need_left = e
            else:
                need_left = None
        return (need_top, need_right, need_bottom, need_left)

    def piece_compat(piece_edges, need):
        """True if piece's rotated edges (n, e, s, w) match the
        constraints `need` (a 4-tuple of color-or-None)."""
        for pe, nd in zip(piece_edges, need):
            if nd is None:
                continue
            if not edge_match(pe, nd):
                return False
        return True

    def score_board(plc):
        """Score the (possibly partial) placement."""
        matched = 0
        for pos, (pid, rot) in plc.items():
            n, e, s, w = pieces_rot[pid][rot]
            x, y = pos % size, pos // size
            # Right edge
            if x + 1 < size:
                rp = pos + 1
                if rp in plc:
                    rpid, rrot = plc[rp]
                    rn, re, rs, rw = pieces_rot[rpid][rrot]
                    if edge_match(e, rw) and e != 0:
                        matched += 1
            # Bottom edge
            if y + 1 < size:
                bp = pos + size
                if bp in plc:
                    bpid, brot = plc[bp]
                    bn, be, bs, bw = pieces_rot[bpid][brot]
                    if edge_match(s, bn) and s != 0:
                        matched += 1
        return matched

    def recurse(pos):
        if timeout[0]:
            return False
        if time.time() - t_start > max_seconds:
            timeout[0] = True
            return False
        nodes_explored[0] += 1
        if pos == n_cells:
            sc = score_board(placement)
            if sc > best['score']:
                best['score'] = sc
                best['placement'] = dict(placement)
            return True  # found a complete placement
        need = cell_constraints(pos)
        # Try each unused piece, each rotation
        for pid in range(n_pieces):
            if used[pid]:
                continue
            for rot in range(4):
                pe = pieces_rot[pid][rot]
                if not piece_compat(pe, need):
                    continue
                placement[pos] = (pid, rot)
                used[pid] = True
                if recurse(pos + 1):
                    # propagate first-solution-found (puzzle is uniquely solvable)
                    return True
                del placement[pos]
                used[pid] = False
        return False

    found = recurse(0)
    elapsed = time.time() - t_start
    exhaustive = found or timeout[0] is False  # found OR fully explored
    if best['score'] < 0:
        # No complete placement found; score the empty
        best['score'] = 0
        best['placement'] = {}
    return best['placement'], best['score'], elapsed, exhaustive


# ----- cross-voting -----

def cross_vote(placements, n_pieces, size):
    """Given a list of K placement dicts, build a consensus placement.

    Voting protocol:
    1. For each cell, count votes per (piece_id, rotation) tuple
       across placements.
    2. For each cell, sort candidate (pid, rot) by vote count desc.
    3. Greedy assign: pick highest-voted (pid, rot) for cell with
       most decisive vote (largest top-1 / top-2 ratio first), then
       second highest, etc. Skip if piece already used.

    Returns consensus placement dict (may have empty cells if greedy
    failed). May not satisfy edge constraints — that's expected.
    """
    n_cells = size * size
    # Tally per-cell votes.
    cell_votes = [{} for _ in range(n_cells)]
    for plc in placements:
        for pos, (pid, rot) in plc.items():
            key = (pid, rot)
            cell_votes[pos][key] = cell_votes[pos].get(key, 0) + 1

    # For each cell, compute top vote and decisiveness.
    cell_top = []
    for pos in range(n_cells):
        v = cell_votes[pos]
        if not v:
            cell_top.append((pos, None, 0, 0))
            continue
        sorted_v = sorted(v.items(), key=lambda x: -x[1])
        top_key, top_count = sorted_v[0]
        runner = sorted_v[1][1] if len(sorted_v) > 1 else 0
        decisiveness = top_count - runner
        cell_top.append((pos, top_key, top_count, decisiveness))

    # Sort cells by decisiveness desc (most decisive first).
    cell_top.sort(key=lambda x: -x[3])

    consensus = {}
    used = [False] * n_pieces
    for pos, top_key, top_count, _dec in cell_top:
        if top_key is None:
            continue
        pid, rot = top_key
        if used[pid]:
            # Find next best (pid', rot') for this cell where pid' not used.
            for (pid2, rot2), cnt in sorted(cell_votes[pos].items(), key=lambda x: -x[1]):
                if not used[pid2]:
                    consensus[pos] = (pid2, rot2)
                    used[pid2] = True
                    break
        else:
            consensus[pos] = (pid, rot)
            used[pid] = True

    return consensus


# ----- main -----

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("puzzle_csv")
    ap.add_argument("--max-seconds-per-relax", type=float, default=120)
    ap.add_argument("--max-seconds-original", type=float, default=600)
    ap.add_argument("--out", default=None, help="JSON output path")
    args = ap.parse_args()

    size, pieces = parse_puzzle(args.puzzle_csv)
    n_pieces = len(pieces)
    print(f"Loaded puzzle: size={size}, pieces={n_pieces}")
    # Count distinct colors in interior edges
    colors = set()
    for p in pieces:
        for c in p:
            if c != 0:
                colors.add(c)
    print(f"Colors present: {sorted(colors)} (count={len(colors)})")

    pieces_rot = [[rotate_edges(p, r) for r in range(4)] for p in pieces]

    # 1. Solve original puzzle
    print(f"\n=== Solving original (no relaxation) ===")
    plc_orig, sc_orig, t_orig, ex_orig = solve_optimum(
        size, pieces, wildcard_color=None, max_seconds=args.max_seconds_original
    )
    n_internal = size * (size - 1) * 2  # 2 * size * (size-1)
    print(f"Original optimum: matched={sc_orig}/{n_internal}, time={t_orig:.2f}s, exhaustive={ex_orig}")
    if sc_orig < n_internal:
        print(f"  WARNING: didn't find full match. Continuing with partial.")

    # 2. Solve relaxed-by-color-k puzzles for k = 1..len(colors)
    relaxed = {}
    for k in sorted(colors):
        print(f"\n=== Solving with color {k} as WILDCARD ===")
        plc, sc, tt, exh = solve_optimum(
            size, pieces, wildcard_color=k, max_seconds=args.max_seconds_per_relax
        )
        # Re-score against ORIGINAL puzzle (no wildcard)
        sc_orig_basis = 0
        for pos, (pid, rot) in plc.items():
            n, e, s, w = pieces_rot[pid][rot]
            x, y = pos % size, pos // size
            if x + 1 < size:
                rp = pos + 1
                if rp in plc:
                    rpid, rrot = plc[rp]
                    rn, re, rs, rw = pieces_rot[rpid][rrot]
                    if e == rw and e != 0:
                        sc_orig_basis += 1
            if y + 1 < size:
                bp = pos + size
                if bp in plc:
                    bpid, brot = plc[bp]
                    bn, be, bs, bw = pieces_rot[bpid][brot]
                    if s == bn and s != 0:
                        sc_orig_basis += 1
        relaxed[k] = {
            'placement': plc, 'score_relaxed': sc, 'score_original': sc_orig_basis,
            'time': tt, 'exhaustive': exh,
        }
        print(f"  Color-{k}-wildcard: matched_relaxed={sc}, matched_against_original={sc_orig_basis}, time={tt:.2f}s")

    # 3. Cross-vote
    print(f"\n=== Cross-voting consensus ===")
    placements = [r['placement'] for r in relaxed.values()]
    consensus = cross_vote(placements, n_pieces, size)
    # Score consensus against original puzzle (no wildcard).
    sc_cons = 0
    for pos, (pid, rot) in consensus.items():
        n, e, s, w = pieces_rot[pid][rot]
        x, y = pos % size, pos // size
        if x + 1 < size:
            rp = pos + 1
            if rp in consensus:
                rpid, rrot = consensus[rp]
                rn, re, rs, rw = pieces_rot[rpid][rrot]
                if e == rw and e != 0:
                    sc_cons += 1
        if y + 1 < size:
            bp = pos + size
            if bp in consensus:
                bpid, brot = consensus[bp]
                bn, be, bs, bw = pieces_rot[bpid][brot]
                if s == bn and s != 0:
                    sc_cons += 1
    print(f"Consensus board: cells_placed={len(consensus)}/{size*size}, score={sc_cons}/{n_internal}")

    # Summary
    max_single_relaxed = max(r['score_original'] for r in relaxed.values())
    mean_single = sum(r['score_original'] for r in relaxed.values()) / len(relaxed)
    print(f"\n=== SUMMARY ===")
    print(f"  Original optimum:         {sc_orig}/{n_internal}")
    print(f"  Max single relaxed (eval against orig): {max_single_relaxed}")
    print(f"  Mean single relaxed (eval against orig): {mean_single:.2f}")
    print(f"  CVC consensus:           {sc_cons}")
    print(f"  CVC vs max single:       {sc_cons - max_single_relaxed:+d}")
    print(f"  CVC vs original opt:     {sc_cons - sc_orig:+d}")

    if args.out:
        out = {
            'size': size, 'colors': sorted(list(colors)),
            'original_score': sc_orig,
            'original_placement': [{'pos': p, 'piece_id': pid, 'rotation': rot}
                                  for p, (pid, rot) in plc_orig.items()],
            'relaxed': {
                str(k): {'score_relaxed': v['score_relaxed'],
                          'score_original': v['score_original'],
                          'time': v['time'],
                          'exhaustive': v['exhaustive'],
                          'placement': [{'pos': p, 'piece_id': pid, 'rotation': rot}
                                       for p, (pid, rot) in v['placement'].items()]}
                for k, v in relaxed.items()
            },
            'consensus_score': sc_cons,
            'consensus_placement': [{'pos': p, 'piece_id': pid, 'rotation': rot}
                                  for p, (pid, rot) in consensus.items()],
            'max_single_relaxed': max_single_relaxed,
            'mean_single_relaxed': mean_single,
        }
        with open(args.out, 'w') as f:
            json.dump(out, f, indent=2)
        print(f"\nSaved to {args.out}")


if __name__ == "__main__":
    main()
