name: Build and Push Envoy Docker Image

on:
  push:
    paths:
      - "envoy/**"
      - .github/workflows/docker-bp-envoy.yaml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-envoy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set lowercase repository name
        run: echo "REPO_LOWERCASE=${GITHUB_REPOSITORY,,}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push envoy image
        uses: docker/build-push-action@v6
        with:
          context: ./envoy
          file: ./envoy/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LOWERCASE }}/envoy:latest
          platforms: linux/amd64,linux/arm64
