name: Build and Push API Docker Image

on:
  push:
    paths:
      - "api/**"
      - "solver/**"
      - .github/workflows/docker-bp-api.yaml
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-api:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build and load docker image
        run: |
          nix build .#grpc-server-docker
          docker load --input result

      - name: Push docker image
        run: |
          docker tag $(docker image list --quiet) ghcr.io/apoorva64/eternity2-grpc-server:latest
          docker push ghcr.io/apoorva64/eternity2-grpc-server:latest
