name: Build and Push Base Docker Image

on:
  push:
    paths:
      - "build-base/Dockerfile"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./build-base
          file: ./build-base/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner | lower }}/${{ github.event.repository.name | lower }}/base:latest
          platforms: linux/amd64,linux/arm64
